name: Terraform Format Check

on:
  pull_request:
    branches: [main]

jobs:
  terraform-fmt:
    name: Terraform Format
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0
      - name: Check formatting
        run: terraform fmt -check -recursive

